package com.team.eb.entity;

// default package
// Generated 2014-8-27 21:26:02 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "ebussiness")
public class Permission implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer permissionId;
	private int parentId;
	private String name;
	private String description;
	private Set<Role> rolePermissions = new HashSet<Role>(0);
	private Set<UserInfo> userPermissions = new HashSet<UserInfo>(0);

	public Permission() {
	}

	public Permission(int parentId, String name) {
		this.parentId = parentId;
		this.name = name;
	}

	public Permission(int parentId, String name, String description,
			Set<Role> rolePermissions, Set<UserInfo> userPermissions) {
		this.parentId = parentId;
		this.name = name;
		this.description = description;
		this.rolePermissions = rolePermissions;
		this.userPermissions = userPermissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "permission_id", unique = true, nullable = false)
	public Integer getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<Role> getRolePermissions() {
		return this.rolePermissions;
	}

	public void setRolePermissions(Set<Role> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<UserInfo> getUserPermissions() {
		return this.userPermissions; 
	}

	public void setUserPermissions(Set<UserInfo> userPermissions) {
		this.userPermissions = userPermissions;
	}

}
