package com.team.eb.entity;

// default package
// Generated 2014-8-27 21:26:02 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info", catalog = "ebussiness")
public class UserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userInfoId;
	private String username;
	private String passwd;
	private String realname;
	private String phone;
	private String email;
	private Date insertTime;
	private boolean deleted;
	private Set<Role> userRoles = new HashSet<Role>(0);
	private Set<Permission> userPermissions = new HashSet<Permission>(0);

	public UserInfo() {
	}

	public UserInfo(String username, String passwd, String realname,
			String phone, Date insertTime, boolean deleted) {
		this.username = username;
		this.passwd = passwd;
		this.realname = realname;
		this.phone = phone;
		this.insertTime = insertTime;
		this.deleted = deleted;
	}

	public UserInfo(String username, String passwd, String realname,
			String phone, String email, Date insertTime, boolean deleted,
			Set<Role> userRoles, Set<Permission> userPermissions) {
		this.username = username;
		this.passwd = passwd;
		this.realname = realname;
		this.phone = phone;
		this.email = email;
		this.insertTime = insertTime;
		this.deleted = deleted;
		this.userRoles = userRoles;
		this.userPermissions = userPermissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_info_id", unique = true, nullable = false)
	public Integer getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(Integer userInfoId) {
		this.userInfoId = userInfoId;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "passwd", nullable = false, length = 50)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "realname", nullable = false, length = 50)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "phone", nullable = false, length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insert_time", nullable = false, length = 19)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<Role> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<Role> userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<Permission> getUserPermissions() {
		return this.userPermissions;
	}

	public void setUserPermissions(Set<Permission> userPermissions) {
		this.userPermissions = userPermissions;
	}

}
